### PR TITLE
SJ201 Fan using the kernel pwm_fan driver

### PR DESCRIPTION
**Pull request by valorekhov**
This replaces `sj201 set-fan-speed 30` on startup with a kernel-managed `pwm_fan` driver monitoring the CPU thermal zone using 4 temperature+fan speed settings.

I wasn't sure where build sources are supposed to be located so, I included the [sj201-pwm-fan-overlay.dts](https://github.com/OpenVoiceOS/ovos-image-arch-recipe/compare/master...valorekhov:ovos-image-arch-recipe:master#diff-d64a3c4d3dce9564c540d060a46a4426bbed8b1f2f141632ebd49f9bab752453) file for the overlay into the `/opt/ovos/builds/sj201` folder on the build image. The `dts` file included instead of the compiled .dbto to allow to easily weak thermal zone trips in source.

The file overlay may be re-built while in the running assistant OS using
```sh
cd /opt/ovos/builds/sj201/
sudo make all
sudo make install
sudo reboot
```

Manual installation shall also require adding to `/boot/config.txt`:
```
dtoverlay=sj201-rev10-pwm-fan
```

To confirm the driver loaded:
```sh
sudo cat /sys/kernel/debug/pwm
```
Should include
```
pwm-1   (sj201-rev10-pwm-fan       ): requested enabled period: 1000000 ns duty: 752941 ns polarity: normal
```
Current fan speed zone may be monitored via:

```sh
watch cat /sys/class/thermal/cooling_device0/cur_state
watch cat /sys/class/thermal/thermal_zone0/temp
```
N.B: It is important that `sj201 set-fan-speed 30` is not ran on startup as it replaces GPIO13 pin 
configuration from hardware to software PWM. 

N.B2: PWM signal logic is inverted. 100% duty (logic 1) means fan is OFF, 0% duty (logic 0) means fan is ON. I couldn't figure out how to invert the PWM via the device tree, Therefore cooling levels are configured in the decreasing order:

```
cooling-levels = <255 192 129 66 0>;
```

### CODE REVIEW

**Comment by builderjer** [comment]
Does this only work on the v10 boards?  All I have is a v6 from the markII dev kit.  I have no real way to test this

**Comment by valorekhov** [comment]
> Does this only work on the v10 boards? All I have is a v6 from the markII dev kit. I have no real way to test this

Yes, this driver is for Rev 10 production boards only, which have the fan control line driven directly from the Broadcom chip's GPIO13 pin. Rev 6 could be theoretically supported through a different overlay using i2c. However, the benefit of reducing load on the main CPU would be marginal in this scenario.

I'm still working out a kink with registering / loading this overlay specifically and only for R10 boards. I'm working on either:
- Loading it dynamically into the kernel's runtime device tree from within [configure_sj201_on_boot.sh](https://github.com/OpenVoiceOS/ovos-image-arch-recipe/blob/master/docker_overlay/overlays/03_sj201/overlay/opt/ovos/configure_sj201_on_boot.sh), or;
- Figuring out the right hook to run one-time logic which will customize `/boot/config.txt` during device provisioning. 
Either of the above is needed to avoid producing release-specific builds (R6 vs R10), which is why I changed the prior approach in [fffb830](https://github.com/OpenVoiceOS/ovos-image-arch-recipe/pull/1/commits/fffb830c4e8e0ffaafc959ff856671d881fcfda7)

**Comment by valorekhov** [comment]
@JarbasAl could you please clarify 26dc66af? Where is the new repo to send this PR to?

@NeonDaniel, would you have any interest in onboarding this [additional PR](https://github.com/NeonGeckoCom/sj201-interface/compare/dev...valorekhov:sj201-interface:dev). I ended up spending a lot of time on getting the Harware PWM Fan logic (subject to the PR on this repo) to co-exist with R10LedFan's NeoPixel. Adafruit's Blinka lib is using `rpi_ws281x` behind the scenes and it is clobbering the PWM settings of a running fan whenever any single LED operation is performed. I added wrapper logic which restores PWM settings allowing the hardware PWM fan to continue operating afterwards

**Comment by JarbasAl** [comment]
> @JarbasAl could you please clarify [26dc66a](https://github.com/LibreVoiceAssistant/libre-image-arch-recipe/commit/26dc66af6f693c69a92bb4061c1b6fbce0b2e5c6)? Where is the new repo to send this PR to?
> 
the original repo has been archived https://github.com/OpenVoiceOS/ovos-image-arch-recipe

the author of this image decided to rebrand and to explicitly not maintain this image as a OVOS community project

A similar PR is very welcome in both our official [buildroot](https://github.com/OpenVoiceOS/ovos-buildroot) images or the community [raspbian-ovos](https://github.com/OpenVoiceOS/raspbian-ovos) image

**Comment by valorekhov** [comment]
> > @JarbasAl could you please clarify [26dc66a](https://github.com/LibreVoiceAssistant/libre-image-arch-recipe/commit/26dc66af6f693c69a92bb4061c1b6fbce0b2e5c6)? Where is the new repo to send this PR to?
> 
> the original repo has been archived https://github.com/OpenVoiceOS/ovos-image-arch-recipe
> 
> the author of this image decided to rebrand and to explicitly not maintain this image as a OVOS community project
> 
> A similar PR is very welcome in both our official [buildroot](https://github.com/OpenVoiceOS/ovos-buildroot) images or the community [raspbian-ovos](https://github.com/OpenVoiceOS/raspbian-ovos) image

.... just as I finally got to an Mk2  that doesn't sound like a jet on take off ...

Well, as an Arch user my preference would've been to continue developing and contributing to this image. I am willing to give it another shot on buildroot, but must say that getting another post-Mycroft flavor (Neon, OVOS, now also Libre) will only add to more confusion in the community.
 
Before proceeding to spend another 2 weeks to build a working Buildroot environment, I would appreciate a confirmation from @NeonDaniel on whether my changes to `sj201_interface` can be added to the repo hosted on his organization. As I wrote, the main complexity of my task was not the enclosure overlays I built for the buttons and the fan, but rather on working around sociopathic  behaviours of the Neopixel lib.

**Comment by JarbasAl** [comment]
we support community maintained images and will give guidance as needed, if you are interested in maintaining the arch image we are happy to give you access to the repo under OpenVoiceOS, we just do not have the bandwidth to take on that responsibility internally

if you are in our matrix chat i'm happy to chat some more about it in a dedicated OVOS channel to not hijack this project, also feel free to open a discussion in https://github.com/orgs/OpenVoiceOS/discussions

as for `sj201_interface` I am certain any PR will be reviewed and much appreciated! that is the official upstream library used for all mk2 integrations in OVOS/Neon ecosystem

**Comment by NeonDaniel** [comment]
> > > @JarbasAl could you please clarify [26dc66a](https://github.com/LibreVoiceAssistant/libre-image-arch-recipe/commit/26dc66af6f693c69a92bb4061c1b6fbce0b2e5c6)? Where is the new repo to send this PR to?
> > 
> > 
> > the original repo has been archived https://github.com/OpenVoiceOS/ovos-image-arch-recipe
> > the author of this image decided to rebrand and to explicitly not maintain this image as a OVOS community project
> > A similar PR is very welcome in both our official [buildroot](https://github.com/OpenVoiceOS/ovos-buildroot) images or the community [raspbian-ovos](https://github.com/OpenVoiceOS/raspbian-ovos) image
> 
> .... just as I finally got to an Mk2 that doesn't sound like a jet on take off ...
> 
> Well, as an Arch user my preference would've been to continue developing and contributing to this image. I am willing to give it another shot on buildroot, but must say that getting another post-Mycroft flavor (Neon, OVOS, now also Libre) will only add to more confusion in the community.
> 
> Before proceeding to spend another 2 weeks to build a working Buildroot environment, I would appreciate a confirmation from @NeonDaniel on whether my changes to `sj201_interface` can be added to the repo hosted on his organization. As I wrote, the main complexity of my task was not the enclosure overlays I built for the buttons and the fan, but rather on working around the sociopathic behaviours of Adafruit's Neopixel lib.

I went ahead and opened a PR from the branch you linked and will try to spend some time testing/reviewing that this week. On a cursory read it looks okay, so I'll just test it for backwards-compat and give it a closer read for any necessary changes/suggestions.

**Comment by valorekhov** [comment]
> we support community maintained images and will give guidance as needed, if you are interested in maintaining the arch image we are happy to give you access to the repo under OpenVoiceOS, we just do not have the bandwidth to take on that responsibility internally
> 
> if you are in our matrix chat i'm happy to chat some more about it in a dedicated OVOS channel to not hijack this project, also feel free to open a discussion in https://github.com/orgs/OpenVoiceOS/discussions
> 
> as for `sj201_interface` I am certain any PR will be reviewed and much appreciated! that is the official upstream library used for all mk2 integrations in OVOS/Neon ecosystem

Thank you, @JarbasAl 
I understand. Fewer but more complete images will be better for this project and community.
I've began looking at the buildroot image to transfer the work there.

**Pull request closed without merging**
